on:
  push:
    branches: main
name: Development Release
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      NAME: Task Concentrator DEV
      TAG_NAME: dev-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Compress
        run: |
          mv dist task-concentrator
          zip -r task-concentrator-${{ env.TAG_NAME }}.zip task-concentrator
      - name: Delete previous tag # This step is to remove the source code asset of the previous release. Otherwise, they will be included in the new release.
        run: gh release delete ${{env.TAG_NAME}} --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: task-concentrator-${{ env.TAG_NAME }}.zip
          prerelease: true
          fail_on_unmatched_files: true
