on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: Development Release
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      NAME_SUFFIX: (DEV)
      TAG_NAME: dev-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock
      - run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Compress
        run: |
          mv dist zero-in
          zip -r zero-in-${{ env.TAG_NAME }}.zip zero-in
      - name: Delete previous tag # This step is to remove the source code asset of the previous release. Otherwise, they will be included in the new release.
        run: gh release delete ${{env.TAG_NAME}} --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: zero-in-${{ env.TAG_NAME }}.zip
          prerelease: true
          fail_on_unmatched_files: true
